### PR TITLE
add animation props to customize appearance of image

### PR DESCRIPTION
**Pull request by flavordaaave**

### CODE REVIEW

**Comment by Pikaurd** [comment]
Good job @flavordaaave

**Comment by oblador** [comment]
Wow, great job! How do you feel about using `react-native-animated` instead?

**Comment by flavordaaave** [comment]
@oblador you mean [react-native-animatable](https://github.com/oblador/react-native-animatable)? I haven't used it before so I'd need to look into that. What would be the advantage compared to the standard react `Animatable` that is currently used?

**Comment by oblador** [comment]
Yep, sorry for the typo. The API seems quite similar so just feels redundant to bake this type of functionality into this component so I then have to maintain similar code in two places.

**Comment by oblador** [comment]
@flavordaaave Did you have a look at the other approach?

**Comment by flavordaaave** [comment]
@oblador Unfortunately now. I'm currently quite busy in my job... I'll try to take some time over the weekend.

**Comment by flavordaaave** [comment]
@oblador I just noticed that custom Image components are now supported. I think someone could then just use `Animatable.Image` from `react-native-animatable` and fire the animation `onLoad` e.g. via `this.imageRef.bounce(900)` or any custom animation that is supported by `react-native-animatable`.
For some reasons the Example is not running for me right now in order to add a quick example but I think this pull request would be obsolete if the above steps would work.

**Comment by flavordaaave** [comment]
@oblador Unfortunately there are two issues with the approach I had in mind. I've created a quick working example:
https://gist.github.com/flavordaaave/0b6ffc0d218f4e4554b3f1340fa26035

The issues that I had to work around:
1) The Example app (in this case app.js) needs to have a reference to the inner `ImageComponent` in order to call the method `transition` or `transitionTo` of the `Animatable.Image` component that is passed to `createImageProgress`.
For demonstration purposes I added a `getComponent` method to `index.js` which allows the app to get the inner `ImageComponent`. I also tried to to get the component from the event (see [here](https://github.com/facebook/react-native/issues/7892)) but I couldn't get it working with that. So maybe you have any other idea about what would be the cleanest approach to that.

2) The app needs to have the possibility to set some initial styles (in the example it is just `{opacity: 0}` to the inner `ImageComponent`. In the example I just hard-coded that initial style directly to within `index.js`. Perhaps we should introduce a new property like `imageStyle` that is passed to the component? Again it's up to you how you'd like to have this ;-)

**Pull request closed without merging**
