### PR TITLE
added npm badge

### PR DESCRIPTION
**Pull request by ochanje210**

### CODE REVIEW

**Comment by oblador** [comment]
Hi & thanks! Sorry for my ignorance, but why is this useful?

**Comment by ochanje210** [comment]
It makes others easy to keep up the npm version and at the same time, it gives you the link to npm website of react-native-image-progress! :D

**Comment by oblador** [comment]
Versions are listed under [releases](https://github.com/oblador/react-native-image-progress/releases) and npm site is identical to github tho?

**Comment by ochanje210** [comment]
You are absolutely right! If you prefer maintaining version information under 'releases' rather than having the badge, it is fine to close this PR. :) I just thought it would be nice to have one!
Here are just information regarding the badges FYI: https://github.com/ochanje210/repo-badges

**Pull request merged**
