### PR TITLE
Replace Image with ImageBackground

### PR DESCRIPTION
**Pull request by kesha-antonov**
https://github.com/oblador/react-native-image-progress/issues/38

### CODE REVIEW

**Comment by oblador** [comment]
Hi, thanks for your contribution!

This change will break backwards compatibility, and can  easily be implemented using the same technique as `ImageBackground` does (and `Image` used to). I've done so in master, so try that one and I'll release this soon unless it causes regressions.

**Comment by kesha-antonov** [comment]
Nice!
Thanks. Will try it tomorrow

**Comment by oblador** [comment]
Any luck? @kesha-antonov

**Comment by kesha-antonov** [comment]
@oblador 

Got some errors:

"Warning: Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onMountComponent() to fire for the child before its parent includes it in onSetChildren().
Invariant Violation: Expected onMountComponent() to fire for the child before its parent includes it in onSetChildren()."

"React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object."

**Comment by kesha-antonov** [comment]
@oblador Tried that. Looks fine!

**Pull request closed without merging**
