### PR TITLE
Added the urlTimeout property, to stop showing an activity indicator when the url is broken.

### PR DESCRIPTION
**Pull request by SudoPlz**
- Added a url timeout timer that makes the progress indicator stop when the image has not completed downloading after `urlTimeout` milliseconds.
- Updated the Readme.md file to let the user know how to change the urlTimeout property if needed.

### CODE REVIEW

**Comment by oblador** [comment]
Doesn't React Native core already send an `onError` on timeouts?

**Comment by SudoPlz** [comment]
Nope! It doesn't.. I had spinners spinning for at least 15  minutes...!

**Comment by oblador** [comment]
Hmm, maybe that should be fixed in RN core instead?

**Comment by SudoPlz** [comment]
No idea, but until it does, this feature is a must have. We can't have an activity indicator running for ever..

**Comment by nmfzone** [comment]
Whoaaa, this is what I wanted...any update on this?

**Comment by oblador** [comment]
@nmfzone This bug should be fixed in [1.0.0](https://github.com/oblador/react-native-image-progress/releases/tag/v1.0.0). Please open an issue if not 👍

**Pull request closed without merging**
